#!/usr/bin/python3
def print_matrix_integer(matrix=[[]]):
    if not matrix:
        return
    for row in matrix:
        for col in row:
            print("{:1d}".format(col), end="")
        print()
